name: Publish npm Package

on:
  # TODO: 差分があるワークスペースとその依存関係についてのみ発火するようにする。
  # 想定としては、このワークフローをuseする親ワークフローがあって、そのワークフロー内で差分解析し、matrixで各ワークスペースで並列実行するようにする。

permissions:
  contents: write
  packages: write

jobs:
  publish:
    name: Publish npm Package
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          token: ${{ secrets.GITHUB_TOKEN }}
          # Defaults to the user or organization that owns the workflow file
          scope: ${{ '@' }}${{ github.repository_owner }}
      - name: Get package name to be released
        id: get-name
        run: node -e "console.log('name=' + require('./package.json').name)" >> "$GITHUB_OUTPUT"
      - name: Get version to be released
        id: get-version
        run: node -e "console.log('version=' + require('./package.json').version)" >> "$GITHUB_OUTPUT"
      - name: Publish npm package
        run: |
          echo "@${GITHUB_REPOSITORY_OWNER}:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NPM_AUTH_TOKEN}" >> .npmrc
          npm install --immutable --immutable-cache --check-cache
          npm publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Add Tag
        run: |
          git tag v${VERSION}
          git push --tags origin v${VERSION}
        env:
          VERSION: ${{ steps.get-version.outputs.version }}
